version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=eventmanagement
      - DB_USER=root
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eventmanagement
    ports:
      - "3306:3306"